### ISSUE TITLE
Automatically add to sys.path

### ISSUE THREAD

**Issue by dschep** [UnitedIncome/serverless-python-requirements#1]
Maybe there's a way to avoid having to add the `import requirements` to your Python files...

**Comment by tonycapone** [comment]
Agree. This plugin is great in theory but having to modify every file in my code to support it is undesirable.

**Comment by tonycapone** [comment]
@dschep why not put the python dependencies in the project root where they would normally be?

**Comment by dschep** [comment]
@tonycapone that just seems to messy, and there'd be no way to easily git ignore all of them. But yeah. that's certainly would take care of it.

**Comment by dschep** [comment]
Also, it would be incompatible with #4 :cry:

**Comment by tonycapone** [comment]
@dschep Yeah that's true, although that messiness is a problem in all Python Aws Lambda projects.

FWIW here's my workaround that mitigated most of the pain:

Put all source code into a local module. Put the Lambda handler file in the project root, and import the module from the handler file. Then you only have to put `import requirements` in the handler file.
