### ISSUE TITLE
Disable/exclude packaging requirements for nodejs functions

### ISSUE THREAD

**Issue by srp-synengco** [UnitedIncome/serverless-python-requirements#102]
Similar to #29, and specifically as mentioned by @trecouvr in https://github.com/UnitedIncome/serverless-python-requirements/issues/29#issuecomment-329426474 it'd be good to disable this plugin for nodejs functions that are sitting next to python functions so the python requirements don't bloat the nodejs functions

Made this separate issue because it's a little bit of a different use case, and hopefully easier to implement? (feel free to close it if it'd just be done with #29 though)

**Comment by dschep** [comment]
Am I right to assume this is for when using the `package.individually=true` option? If so, #117 will fix this!

**Comment by srp-synengco** [comment]
Cool! 👍 Wasn't using `package.individually=true` yet in case i didn't need to, but I think that's a decent approach, thanks 😄

**Comment by dschep** [comment]
Awesome. I'll close this when I merge and release that feature.
