### ISSUE TITLE
Fails on windows because of symlink

### ISSUE THREAD

**Issue by trondhindenes** [UnitedIncome/serverless-python-requirements#11]
I'm getting this error when executing serverless deploy on Windows:
EPERM: operation not permitted, symlink '.requirements\requests'

**Comment by dschep** [comment]
Hmm. Does node js's symlink stuff work on windows?

**Comment by trondhindenes** [comment]
I have no idea, I dont do node. Just trying to get python to work with serverless in a somewhat seamless way.

**Comment by dschep** [comment]
Hah. I'll look into it when I get a chance to setup node on a windows box (I don't do windows :stuck_out_tongue: )

**Comment by trondhindenes** [comment]
:-) I got around it by just running the serverless deploy commands in a container, so it's no biggie.
Regarding nodeJS and symlink support, this could be of interest: https://github.com/nodejs/node-v0.x-archive/issues/2274 (I haven't tried running the serverless deploy command as admin)

**Comment by dschep** [comment]
Ah, that definitely is of interest. Thanks! Current docs don't seem to mention this limitation, but does mention a few others.

**Comment by AndrewFarley** [comment]
This bug can be closed, the current codebase does not use any symlinks

**Comment by dschep** [comment]
Good point @AndrewFarley
