### ISSUE TITLE
Is it possible to specify a different requirement.txt file per function?

### ISSUE THREAD

**Issue by amitm02** [UnitedIncome/serverless-python-requirements#119]
Is it possible to specify a different requirement.txt file per function in the serverless.yml function?
Currently all my functions are getting inflated because of requirements needed by another specific function.

**Comment by dschep** [comment]
Not currently, no.  You might want to check out the serverless-python-individually plug-in, tho it doesn't feature docker support.

**Comment by cgrimal** [comment]
Hi  @amitm02,

I had the same problem of inflated functions, and event though I noticed some plugins were available, I still wanted to be able to use the more advanced features of this plugin (like dockerized pip + private repos + custom Dockerfiles, etc.) so I decided to implement the per-function requirements in this plugin.

Should be available soon though: https://github.com/UnitedIncome/serverless-python-requirements/pull/131
