### ISSUE TITLE
invoke local issue

### ISSUE THREAD

**Issue by cm-usuda-keisuke** [UnitedIncome/serverless-python-requirements#12]
I think the old this plugin could invoke local command e.g. 'sls invoke local'.
However can't invoke local now.
I saw the following error.
```
ImportError: No module named unzip_requirements
```
The cause of issue is to remove unzip_requirements after zip in deploy flow.
Could you fix it?

**Comment by dschep** [comment]
Hmm. Good point. (I actually implemented `sls invoke local` for python upstream :smile: )

**Comment by cm-usuda-keisuke** [comment]
@dschep Thank you for the update!
I'll check the new option.
