### ISSUE TITLE
Bootstrap numpy installation

### ISSUE THREAD

**Issue by cgrimal** [UnitedIncome/serverless-python-requirements#126]
Hi guys,

I have a private repository with C extensions. The `setup.py` file requires Numpy, so you need to have it installed on your system before building the package.
I run into a problem when using the `dockerizePip` option, because Numpy is not installed in the docker container.

I found 2 possible workarounds:

1. Change the `setup.py` of my project to bootstrap installation of Numpy (see this [stackoverflow post](https://stackoverflow.com/questions/19919905/how-to-bootstrap-numpy-installation-in-setup-py)).
**PROS:** project is more straightforward to install, and nothing has to be changed to this plugin.
**CONS:** Numpy is built at every deploy, and it is very long.
2. Add a `bootstrapNumpy` option to this plugin, that if true, will do a `pip install numpy` before running the install of the requirements.
**PROS:** fast and flexible.
**CONS:** Yet another option...

To be honest, the first option is not viable for me, because IMO building Numpy at every deploy is killing it. So I am using a dirty local version to implement the second option.
That being said, if someone run into the same issue, and if you think it might be useful to others, I can submit a PR.

Thanks!

**Comment by dschep** [comment]
I would prefer the third option which is to implement #114, then you could just have:

Dockerfile:
```dockerfile
FROM lambci/lambda:build-python3.6
RUN pip install numpy
```

sls.yml:
```yaml
custom:
  dockerizePip: true
  dockerFile: Dockerfile

**Comment by cgrimal** [comment]
Agreed! This is a much more flexible and elegant solution.
Will try to look into it.
