### ISSUE TITLE
More lenient timeout for Dockerfile case

### ISSUE THREAD

**Issue by woozyking** [UnitedIncome/serverless-python-requirements#133]
Currently, the docker command timeout config (10 seconds) would often result in a `spawnSync` timeout error when the image is to be built from `Dockerfile` for the first time.

Can we consider removing the timeout or giving a very lenient timeout for the Dockerfile case?

**Comment by woozyking** [comment]
The workaround is usually just "pre-build" the image using `docker build ./` before invoking `sls deploy`.

**Comment by dschep** [comment]
Seems reasonable to me. @cgrimal is there a reason you included a time out on the docker `spawnSync` calls?

**Comment by cgrimal** [comment]
No not really. I used the same timeout as other uses of the `spawnSync` function. We can either increase it, use an additional option to pass the timeout value, or ask the user to pre-build the image.

**Comment by dschep** [comment]
AFAICT other uses of `spawnSync` don't specify a timeout. And the default is `undefined` http://devdocs.io/node~6_lts/child_process#child_process_child_process_spawnsync_command_args_options

**Comment by dschep** [comment]
I've pushed an update to master @woozyking. Could you test it out by installing as `npm i UnitedIncome/serverless-python-requirements` and trying again? (probably delete the image you've built before)

**Comment by woozyking** [comment]
@dschep I just tested this with `lambci/lambda` based Dockerfile (with no `lambci/lambda` image on local), and this is working as intended.

`SLS_DEBUG` settings may be further utilized to print out what `docker` command's doing behind the scene though, as psychologically, it does make people anxious when there's nothing shown while waiting for images/layers being pulled/downloaded (which may explain why the timeout was there in the first place 🤣 )
