### ISSUE TITLE
Log pip&docker stdout/stderror when using sls -v

### ISSUE THREAD

**Issue by dschep** [UnitedIncome/serverless-python-requirements#160]
woudl help with debugging issues like #135

**Comment by notEvil** [comment]
This would help a lot! I have problems with pip install too, but the plugin would ignore any output of pip. Afaik you just need to set `stdio: 'inherit'` for `spawnSync` in case of verbose. Any reason why this is not implemented yet?

**Comment by dschep** [comment]
I've got tons on my plate and haven't needed the feature myself yet. I'll happily review and merge a PR doing what you described @notEvil

**Comment by twonds** [comment]
I am having an ssh key issue and needed this, the PR is simple and may not be complete.

**Comment by bsamuel-ui** [comment]
Closing as it looks fixed.
