### ISSUE TITLE
Unable to use custom repository

### ISSUE THREAD

**Issue by MichaelBellBOM** [UnitedIncome/serverless-python-requirements#176]
I am working on deploying a lambda function that uses custom libraries stored in Artifactory.  Unfortunately when running `sls deploy`, the plugin fails because the `--isolated` argument causes the settings point towards our custom repository to be ignored and the jobs fails as it cannot find our custom library?

What is the reason for using the `--isolated` argument?  And might it worth making it a parameter that could be overwritten?

**Comment by dschep** [comment]
Hmm. It seems I added that based on an early suggestion (#8). But since then the [`pipCmdExtraArgs`](https://github.com/UnitedIncome/serverless-python-requirements#extra-pip-arguments) option, so I think it makes sense to remove it so that custom repos, etc. can work.

**Comment by dschep** [comment]
Released as v4.0.1
