### ISSUE TITLE
How Do I deploy a function with python packages in private pip server

### ISSUE THREAD

**Issue by gerbenbas** [UnitedIncome/serverless-python-requirements#177]
Hi everyone,

I’ve been using the serverless framework for a while to deploy functions that use python packages. For that purpose, I have been using the serverless-python-requirements plugin. This all works great. However, I now want to deploy a function that uses a python package that is hosted at a private pip server.

Locally, I add this pip server to my pip.conf file like this:
```
[install]
extra-index-url = https://$USERNAME:$PASSWORD@$URL/simple/

```
This works great when I install a package on my own device. However, when I try to deploy my function with the private python package in the requirements.txt, I get the following error:

```
Error --------------------------------------------------

   Could not find a version that satisfies the requirement
 $PACKAGE_NAME (from -r .serverless/requirements.txt
 (line 11)) (from versions: )
No matching distribution
found for $PACKAGE_NAME (from -r .serverless/requirements.txt
(line 11))
```

It thus appears to me that the python requirements plugin uses the regular pip server and not the private pip server that I configured and use when I run pip install $PACKAGE_NAME.

Does any of you have an idea on how I can configure serverless so that it uses the private pip server?

Thank you in advance,

Gerben

**Comment by dschep** [comment]
Are you using the [`dockerizePip`](https://github.com/UnitedIncome/serverless-python-requirements#cross-compiling) option?

**Comment by dschep** [comment]
If not, this looks like it might be related to #176 and the use of `--isolated`.

**Comment by dschep** [comment]
In that case, try out v4.0.1 which should fix the issue.

**Comment by dschep** [comment]
Excellent!

**Comment by jasonkuhrt** [comment]
I'm getting this error and I have these versions:

```json
{
  "name": "unresponsive",
  "description": "foobar",
  "license": "UNLICENSED",
  "repository": "github:dialoguemd/unresponsive",
  "version": "0.1.0",
  "dependencies": {},
  "devDependencies": {
    "serverless-pseudo-parameters": "^1.6.0",
    "serverless-python-requirements": "^4.0.3",
    "serverless-step-functions": "^1.4.1"
  }
}

```

**Comment by jasonkuhrt** [comment]
Maybe relevant is that:

- I am using `pipenv`
- I am adding support for the other index via env var: `PIP_EXTRA_INDEX_URL`
