### ISSUE TITLE
How to speed up packaging with multiple lambda functions and package individually set to True?

### ISSUE THREAD

**Issue by skeller88** [UnitedIncome/serverless-python-requirements#183]
This library has been helpful, but I'm running into performance limits. At 5 lambda functions with per package requirements and the `dockerizePip` option, the `package` step is taking 5 minutes. With "package individually" set to "True", that step takes 1.5 minutes. That's great, but I need the individual packaging to stay under the lambda deployment package size limit. How can I speed up the package step? 

Creating a docker image with all of the dependencies would probably help. I'm going to try that. 

Is there a way to just package a single lambda function? It doesn't seem like there is. Is there a way to parallelize the packaging of lambda functions? Also doesn't seem like there is.

**Comment by dschep** [comment]
Yeah I'm not sure what to do about that. Your right AFAIK that there's only "full service" `sls package` and that packaging of the functions not being parallel is probably how sls does it :confused:

**Comment by skeller88** [comment]
Right. How has the lambda process scaled for you guys then? I would assume you have dozens of lambdas or more at this point. 

One way to get around the Serverless packaging slowness could be to have several build processes, each of which does a different subset of the lambdas.

**Comment by dschep** [comment]
We don't use `package: individually`, so we're just building 1 package (and have relatively few dependencies)

**Comment by skeller88** [comment]
Gotcha. Well I'd be fine with this issue being closed then. Sounds like a feature request for the Serverless Framework :).
