### ISSUE TITLE
Docker build fails if space in Path

### ISSUE THREAD

**Issue by JonnyWaffles** [UnitedIncome/serverless-python-requirements#184]
Hi. When trying to build a test project following this [tutorial](https://serverless.com/blog/serverless-python-packaging/) on Windows 10 in the following directory `C:\Users\Jonny Waffles\PycharmProjects\numpy_test` I received the following error during deployment:

```Serverless: Docker Image: lambci/lambda:build-python3.6

  Error --------------------------------------------------

  docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
```

However, if I built the project out of a directory with no spaces it succeeded:

`C:\testproject`

**Comment by rob-deans** [comment]
Still have the same problem with this, have version 4.2.2.

My path does have a spaces in, moving to another again succeeds

**Comment by rob-deans** [comment]
Windows 10 Pro v 1803

**Comment by dschep** [comment]
Ahh. Ok. I was gonna be surprised if it wasn,t since there's test coverage for that, but tests are run on linux in CI only. see #249  for more about that. As for the bug. good catch. @vecchp, you removed quoting on windows in #247. Do you know if there's a windows equivalent of `shell-quote`?
