### ISSUE TITLE
Don't dockerize when run requirements install

### ISSUE THREAD

**Issue by eloyvega** [UnitedIncome/serverless-python-requirements#19]
Usually you do "sls requirements install" for local testing, but if you have "dockerizePip: true" on serverless.yml it will download the linux libraries. This is a problem if you want to make a "sls invoke local" on another environment. I think is best to use the docker container only when "sls deploy"

**Comment by dschep** [comment]
I suggest using a virtualenv and normal pip installation for local development like you would an ordinary(non-serverless) python project.
