### ISSUE TITLE
Keep a changelog?

### ISSUE THREAD

**Issue by taion** [UnitedIncome/serverless-python-requirements#192]
Hi! Thanks for your work on this library.

We're currently in the process of upgrading some of our dependencies. We noticed that this library recently upgraded to v4. However, we can't find a changelog for the breaking differences between v3 and v4.

Would it be possible to keep a changelog? Although – if there is one and I just missed it, apologies in advance.

**Comment by dwolfand** [comment]
@taion - I agree that we can do a better job surfacing this information, thanks for raising the issue. Most of the features/flags weren't drastically changed from v3 to v4 but a lot was changed under the hood to better support caching and  per-function requirements. @dschep is on vacation but can speak to this in more detail once he gets back next week and we'll definitely get better about documenting these changes in the future.

**Comment by dschep** [comment]
Thanks for the extra nudge to do what we should already be doing @taion. For your immediate querstion, the main difference between v3 & v4 is how the libraries are added to the zip. In v3 it was symlinking libraries from `.serverless/requirements` then letting sls's packaging occur then unlinking them. In v4 libraries are now directly injected into the zip after sls's packaging occurs.

**Comment by taion** [comment]
Thank you!

**Comment by dschep** [comment]
Hey @taion I never got around to this, but I did just realize, I've been pretty consistent in including notes in release tags, check those out here: https://github.com/UnitedIncome/serverless-python-requirements/tags

click the `...` to expand the notes

**Comment by taion** [comment]
Ah, that's cool, thanks!

For what it's worth, it's relatively easy to convert those to GitHub releases. That's actually not an uncommon way to keep changelogs anyway.

**Comment by dschep** [comment]
Thats a good idea, esp since releases are easy to edit, so I can flesh out the releases that had skimpy release notes

**Comment by taion** [comment]
Yup – it looks pretty nice on the GitHub page, too, e.g.: https://github.com/4Catalyzer/found/releases

Thanks!
