### ISSUE TITLE
Cross compile modules when not on x86_64 Linux

### ISSUE THREAD

**Issue by dschep** [UnitedIncome/serverless-python-requirements#2]
Unfortunately not everyone accepts 🐧 power on their desktop, so this should probably cross compile modules with C extensions.

references:
 * http://whatschrisdoing.com/blog/2009/10/16/cross-compiling-python-extensions/
 * https://pypi.python.org/pypi/distutilscross

**Comment by glb** [comment]
There's an Amazon Linux Docker image that may be useful for this purpose ... I've been playing around with the attached but haven't gotten to something that's completely baked yet.
```
rm -rf output
mkdir output
docker build -t build-native .
docker run -v $PWD/output:/output build-native /build.sh native-module1 ...
```
[build-native.zip](https://github.com/UnitedIncome/serverless-python-requirements/files/654613/build-native.zip)

**Comment by dschep** [comment]
Awesome @glb, Docker was one of my first thoughts too :smile:
