### ISSUE TITLE
Latest version throws `Unexpected token ...`

### ISSUE THREAD

**Issue by trondhindenes** [UnitedIncome/serverless-python-requirements#20]
Somewhere between 2.0.0 and latest some error was introduced which started failing our builds. I'm unable to troubleshoot more than verifying that the error is not present in 2.0.0.

Error msg: 
`Unexpected token ...`

**Comment by dschep** [comment]
You're probably using node 4. The plugin now requires node 6. It's definitely possible to implement the changes in a way that works in 6 but we had no need for node 4 support and I'd already written it with out realize it wasn't compatible with node 4 so i just bumped the node dep.

**Comment by trondhindenes** [comment]
ok thanks. I saw the warning message for the node version - might be a good idea to use a hard instead of soft dependency (if npm/node supports anything like that)
