### ISSUE TITLE
"sls package" stucks on "Injecting required Python packages to package..."

### ISSUE THREAD

**Issue by amitm02** [UnitedIncome/serverless-python-requirements#206]
I've tried to use the new version (4.0.5)
I have some big libraries in the requirement.txt file:
```
opencv-python-headless
numpy
```

When run:
`sls package`

the console was stuck on "Injecting required Python packages to package...". (or so it seems, it runs forever). Node process is at 100% cpu.

When tired on version 3.3.1, everything works normally.

**Comment by dschep** [comment]
Could you provide some more details please? your sls config, and platform mostly.

**Comment by amitm02** [comment]
The platform is OS X (mac). Ill send the sls config tomorrow once I access
to the computer.

**Comment by amitm02** [comment]
what do you mean by sls config? the serverless.yml file?
I'm not sure i can send the original due to company IP and stuff. 

I have noticed that if i set individually to "false":
```
package:
  individually: true
```
It works again.
Could it be that if the individually is set to true and but function "module" is not defined to goes crazy?

**Comment by dschep** [comment]
Ah, yes. that's probably it.

**Comment by dschep** [comment]
cc @cgrimal

**Comment by cgrimal** [comment]
Hi guys,

If the package individually option is set to true, but a function has no module property, it assumes the module is your local directory. So the process should not go crazy, but should be looking for a requirements.txt file at the root of the project.

I understand you can't share the real content of your serverless.yml file, but please take some minutes to build a minimal example of project to demonstrate the bug. It will help us identify and fix the bug.

Many thanks,
Clément

**Comment by miketheman** [comment]
I tested this today with plugin version 5.1.0, with the information available.

I was able to complete packaging with both `individually: true` and without, and it was successful.

I'm going to close out this issue, please reopen or create a new one referencing this one with further details.
