### ISSUE TITLE
"process.getuid is not a function" on Windows

### ISSUE THREAD

**Issue by ChrisAnn** [UnitedIncome/serverless-python-requirements#21]
`process.getuid is not a function` error when running on Windows.  This seems to be a POSIX only function.

Are you able to conditionally exclude it?

**Comment by dschep** [comment]
Does `-u` on docker similarly not exist then? Or rather, how does windows + docker deal with user issues?

**Comment by ChrisAnn** [comment]
I haven't yet played with docker.  I'll ask around.

**Comment by ChrisAnn** [comment]
Come to think of it, could you create the docker command only when the project specifies it'll be dockerizing the packages?  As I'm not using docker, this will become a non-issue for me.

**Comment by dschep** [comment]
Good call. I didn't realize I was creating the command for docker even if it isn't being used. Should be an easy fix, I'll do it when I get the chance.

**Comment by dschep** [comment]
@ChrisAnn, you should be able to use v2.1.2 that I just pushed. I'll leave this issue open tho to track the fact that the dockerize option doesn't work on windows.

**Comment by FelschR** [comment]
I tried 2.1.2 and 2.3.3 and I get the error on Windows.

**Comment by dschep** [comment]
@FelschR are you trying to use docker? If so, do you know the answer to my above question about a `-u` flag?

**Comment by FelschR** [comment]
@dschep Yes, I was. I'll check it next week.

**Comment by FelschR** [comment]
The help for `docker run` lists:
```
  -u, --user string                    Username or UID (format:
                                       <name|uid>[:<group|gid>])
      --userns string                  User namespace to use
      --uts string                     UTS namespace to use
```

**Comment by FelschR** [comment]
Oh, I stumbled upon the node.js documentation for `process.getuid()` and it actually statesthat it's only available on POSIX platforms;
https://nodejs.org/api/process.html#process_process_getuid

**Comment by dschep** [comment]
Cool Thanks. Yeah i knew the nodeJs side of the story, was unsure of the docker side. That looks like maybe on window It could fall back to `process.env.USERNAME`. Could you try the branch I just pushed relating to this? `npm install unitedincome/serverless-python-requirements#docker-windows`

**Comment by FelschR** [comment]
@dschep as far as I can tell it's working.
Although I now get a different error:
```
Serverless: Installing required Python packages for runtime nodejs6.10...

  Type Error ---------------------------------------------

  Cannot read property 'toString' of null
```

**Comment by dschep** [comment]
Ah, that makes sense that the user wouldn't exist in the linux VM that docker for windows creates. I guess i'll just completely skip the `-u` option on windows, barring a better option. I'll whip that up when I have some downtime again.
