### ISSUE TITLE
File Permissions are not preserved

### ISSUE THREAD

**Issue by hunterclarke** [UnitedIncome/serverless-python-requirements#233]
I'm running a python function that calls a binary that ships within an individually packaged module. However, when packaged, the file's permissions as an executable are not transferred (they are preserved without this plugin). Any ideas as to how to debug this? I'd be happy to submit a PR but I can't figure out where in the process these permissions would be getting stripped.

**Comment by bsamuel-ui** [comment]
We ran into this before, #178 fixed #166.

**Comment by bsamuel-ui** [comment]
In a nutshell, the permissions were getting stripped because an older zip library didn't save them, and JSZip 3.x solved the issue.

**Comment by dschep** [comment]
Could you share your `package.json` and `serverless.yml`? or at least the versions of the framework & plugin and what options you're setting for the plugin.

**Comment by hunterclarke** [comment]
Here is a bit more context (sorry for the bare comment before, I didn't know if this had an easy fix):

Versions:
serverless: `1.30.3`
serverless-python-requirements: `4.1.1`

`serverless.yml` contains:
```yml
package:
  individually: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
```

The function in particular has a `requirements.txt` file with:
```
requests==2.18.1
urllib3==1.22
```
And the function contains a directory structure:
```
pdf2htmlex
├-- README.md
├-- main.py
├-- preview.min.css
├-- src
  ├-- bin
    ├-- pdf2htmlEX
```

`pdf2htmlEX` is the executable.

In the project this has the permissions:
```
-rwxrwxrwx  1 503  20  548200 Sep  7 07:20 pdf2htmlEX
```

However, I noticed on running `sls package` and extracting the results from the zip, the file has the permissions:
```
-rw-rw-r--  1 503  20  548200 Dec 31  2097 pdf2htmlEX
```

**Comment by bspink** [comment]
I'm seeing this issue when trying to run [awscli](https://github.com/aws/aws-cli) (to use the `s3 sync` command) inside of a lambda.

The permissions for the `aws` binary have the executable bit set locally after installing with `pip` into my virtualenv, but inside of the package zip file created by serverless, the executable bits have been stripped.

I tested by running `ls -alh` on the `/var/task/bin` dir inside the lambda, and the same permissions are there as well.

**local permissions**:
```bash
(build-deploy-python) ➜ ls -al /Users/bspink/.virtualenvs/build-deploy-python/bin/aws
-rwxr-xr-x  1 bspink  staff  859 15 Mar 09:46 /Users/bspink/.virtualenvs/build-deploy-python/bin/aws
```

**lambda permissions**:
```bash
drwxrwxr-x 3 root root 573 Mar 15 00:03 .
drwxr-xr-x 23 root root 740 Mar 15 00:04 ..
-rw-rw-r-- 1 root root 822 Jan 1 2098 aws
-rw-rw-r-- 1 root root 204 Jan 1 2098 aws_bash_completer
-rw-rw-r-- 1 root root 1.4K Jan 1 2098 aws.cmd
-rw-rw-r-- 1 root root 1.2K Jan 1 2098 aws_completer
-rw-rw-r-- 1 root root 1.8K Jan 1 2098 aws_zsh_completer.sh
```
