### ISSUE TITLE
Support pipenv?

### ISSUE THREAD

**Issue by trondhindenes** [UnitedIncome/serverless-python-requirements#234]
It would be awesome to see this package supporting pipenv (https://pipenv.readthedocs.io/en/latest/). We're switching all our repos from simple requirements.txt to pienv because of the increased control, especially with the implementation of a lockfile. We're also using some internal and some external packages, and pipenv allows us to specify sources and link packages to sources.

Without having looked at the code for the serverless-python-requirements repo I have a feeling that it wouldn't take too much work to support pipenv. If there's interest I can check if I'm able to convince a few of the node/js devs on my team to help out.

**Comment by dschep** [comment]
How hard did you look? 😛 

It already supports pipenv: https://github.com/UnitedIncome/serverless-python-requirements#pipenv-support-sparklescakesparkles

**Comment by trondhindenes** [comment]
Now I feel stupid. Thanks, this is awesome!!
