### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by pshendry** [UnitedIncome/serverless-python-requirements#24]
AWS Lambda now has [a Python 3.6 runtime](https://aws.amazon.com/about-aws/whats-new/2017/04/aws-lambda-supports-python-3-6/). I tried switching my runtime to `python3.6` but my functions are failing due to packaging-related errors (`module initialization error: psycopg2 must be installed.`), so I'd imagine some action needs to be taken here to support this.

I took a look at the source and it looks like `pip` is being invoked from the path, so I tried activating a venv with `python3 -m venv venv; venv/bin/activate` and then invoking `sls deploy`, but I got the same result. I'm not sure that the `pip` version used matters, when it's going to a specified path anyway, but perhaps it does?

**Comment by dschep** [comment]
I'll take a look. It's just a matter of calling `pip3`.  Tho I don't think psycopg works on lambda because there's no `libpq` on those boxes 😕

**Comment by pshendry** [comment]
Thanks for tackling this, much appreciated!
