### ISSUE TITLE
v4.2.0 breaks deployment in path containing spaces

### ISSUE THREAD

**Issue by notEvil** [UnitedIncome/serverless-python-requirements#242]
Hope its reproducible. The error message says

    Invalid requirement: {part after space}
    It looks like a path. File {part after space} does not exist.

v4.1.1 works just fine

**Comment by AndrewFarley** [comment]
I'll look into this now... @notEvil can you provide your current file path, OS, serverless.yml and requirements.txt for me incase I need it for further debugging.  Thanks!

**Comment by notEvil** [comment]
I can reproduce with minimal setup

path: $HOME/directorywith space/
OS: Linux Mint 18.3

serverless.yml:

    service: tspace

    provider:
        name: aws

    functions:
        space:
            handler: handler.handle

    plugins:
      - serverless-python-requirements

requirements.txt:

    -i https://pypi.org/simple
    boto3

yes it could be setup specific, but as everything works when fixing version to 4.1.1, I thought its not necessary

**Comment by AndrewFarley** [comment]
@notEvil Give me a few minutes to finish some other work and I'll do some digging, I couldn't replicate it on my machines, but thanks... right off the bat I can tell you your requirements looks suspicious because it doesn't actually have any (usable) contents in it.  Boto3 is skipped since it's auto-included on AWS Lambda.  If you want to save me some effort, can you try putting something besides boto3 in there?  Eg: pyyaml?  And tell me if that works?  Thanks, and I'll get back to you shortly.

**Comment by dschep** [comment]
Interesting. I've added a test that proves this: 837f063

**Comment by AndrewFarley** [comment]
Yeah, I found the bug also, I'm fixing it now.  :)  Thanks for the test!

**Comment by AndrewFarley** [comment]
@notEvil Can you please try the following merge request see if this fixes your problem, from within your project... I confirm this fixes all tests, all options, etc, on Ubuntu and Mac.  Thanks for the bug report, and sorry about this!
```
rm -Rf node_modules/serverless-python-requirements
npm i github:andrewfarley/serverless-python-requirements#bug-space-paths
sls package
```

**Comment by AndrewFarley** [comment]
@Nihilight Ah yeah, I can't win... that's a different issue, but related to this fix.  Ugh...  :P  Can you get me more details on your setup?  as much as you can from your serverless.yml, requirements.txt, your cwd, your OS, etc.  Maybe open a new bug for me with those details and I'll see if I can replicate and fix it for you.

**Comment by Nihilight** [comment]
Done. #245

**Comment by notEvil** [comment]
@AndrewFarley it works, thanks a lot
