### ISSUE TITLE
4.2.1 introduces requirements path problem in Windows

### ISSUE THREAD

**Issue by hubbins** [UnitedIncome/serverless-python-requirements#248]
4.2.0 works correctly

This path gets changed from:
D:\work\git\something-game\game-rank-notifier\.serverless\requirements

To:
`D\:\\work\\git\\something-game\\game-rank-notifier\\.serverless\\requirements`

By the newly added function quote_single().  This doesn't seem to have been tested in Windows.

Thanks

**Comment by hubbins** [comment]
Edited initial post to put the "To" path in a code block to preserve formatting.

**Comment by hubbins** [comment]
Correction, introduced in 4.2.1.

**Comment by dschep** [comment]
#247 will fix this AFAIK.

**Comment by hubbins** [comment]
Actually 4.2.2 introduced this, but it doesn't seem like there were changes in this area for 4.2.2?

**Comment by hubbins** [comment]
> 
> 
> #247 will fix this AFAIK.

Seems like it.  Thanks

**Comment by dschep** [comment]
Released fix as v4.2.3
