### ISSUE TITLE
Upgrade to serverless 1.12 lifcycle hooks

### ISSUE THREAD

**Issue by dschep** [UnitedIncome/serverless-python-requirements#25]
Relevant docs:
* https://serverless.com/blog/serverless-v1.12.0/#an-important-note-for-plugin-authors
* https://github.com/serverless/serverless/blob/07f837ddb67a40cee3e0c6b238e165023b4b7725/lib/plugins/deploy/deploy.js#L14-L19
* https://gist.github.com/HyperBrain/bba5c9698e92ac693bb461c99d6cfeec

**Comment by cscetbon** [comment]
@dschep any reason why this one is closed ?
