### ISSUE TITLE
Failed to load requirements.txt on Windows with dockerizePip set to false

### ISSUE THREAD

**Issue by PatrickBuTaxdoo** [UnitedIncome/serverless-python-requirements#252]
The `sls deploy` command fails if dockerizePip is set to false while using a windows system:
```
Could not open requirements file: [Errno 22] Invalid argument: 'C\\:\\\\Users\\\\[...]\\\\.serverless\\\\requirements\\\\requirements.txt'
```
There are way too many slashes. I think the error originates from this function in `lib/pip.js`:
```
function dockerPathForWin(options, path) {
  if (process.platform === 'win32' && options.dockerizePip) {
    return path.replace(/\\/g, '/');
  }
  return quote_single(path);
}
```
It should instead look like this:
```
function dockerPathForWin(options, path) {
  if (process.platform === 'win32') {
    return path.replace(/\\/g, '/');
  }
  return quote_single(path);
}
```

**Comment by dschep** [comment]
That's probably right. Did you test this change? Either way, feel free to make a PR. I'll cut a release if this fix is confirmed, but I don't have a windows box.
