### ISSUE TITLE
Serverless Python Requirements without the Docker

### ISSUE THREAD

**Issue by kyeljmd** [UnitedIncome/serverless-python-requirements#273]
Hi.

We are programming in a very closed and strict environment. Given the nature of the policies that we have on our machines enabling, and deploying with Docker is not possible. This plugin looks promising and will greatly benefit us. My question is there any support for serverless python requirements without using Docker? at the moment we dont have the need to do cross compilation of our dependencies.

**Comment by dschep** [comment]
Yup, what @AndrewFarley said. Docker use is entirely optional and off by default.
