### ISSUE TITLE
Support for poetry?

### ISSUE THREAD

**Issue by squaresurf** [UnitedIncome/serverless-python-requirements#306]
What are the thoughts for supporting [poetry](https://github.com/sdispater/poetry)? It has an export command `poetry export` that can create a requirements.txt file which means it could have a similar approach as current pipenv support.

**Comment by dschep** [comment]
I'd be glad to accept a PR using the same technique as Pipenv since that seems possible.

**Comment by miketheman** [comment]
Poetry is now supported!
