### ISSUE TITLE
Check that specified runtime exists in the PATH

### ISSUE THREAD

**Issue by pshendry** [UnitedIncome/serverless-python-requirements#31]
If you specify a runtime that you don't have installed (for example, in my case python3.6 in Ubuntu 16.04 which only has Python 3.5 installed by default), you get a confusing error: `Cannot read property 'toString' of null`. This is because we don't check that `runtime` exists in the path; we invoke it and assume that there will be `stdout` output.

An explicit check to see if the specified runtime is available would save dummies like me a bunch of confusing digging through source code in order to figure out that they don't have the right version of Python installed :smile:

**Comment by dschep** [comment]
Good idea, especially with most people not having python 3.6 on their computers.

**Comment by Mortinke** [comment]
I run in the same issue. This means, this plugins needs python3.6?

**Comment by dschep** [comment]
@Mortinke if you're targeting py3.6, yes.
