### ISSUE TITLE
Pipenv including development dependencies

### ISSUE THREAD

**Issue by revmischa** [UnitedIncome/serverless-python-requirements#322]
Maybe related to #113 -

I may be using something wrong, but I would expect dev dependencies from pipenv to not be included with the serverless package, yet it seems they are. My function doesn't need pytest, flake8, etc etc. I know I can exclude them, but I would expect them to not be included as they are listed as dev dependencies in my pipfile.

**Comment by kstohr** [comment]
I am having the same issue running the following to export a requirements.txt file: 
```
pipenv lock -r 
```
Need an easy way to exclude --dev dependencies. 

I have read through some of the various issues related to this and it seems it was supposed to be added as a  feature in 9.0.0. What is the status?

**Comment by miketheman** [comment]
@revmischa I recently added a test in #466 to verify that the dev deps are not included in the package. Going to close this out - please reopen or open a new issue with details that we can use to reproduce.
