### ISSUE TITLE
Serverless failing to deploy when "serverless-python-requirements" is installed

### ISSUE THREAD

**Issue by DrColza** [UnitedIncome/serverless-python-requirements#333]
Hello, 

Given I've just been deploying my serverless application without issue
When I installed the "serverless-python-requirements" package
Then I get the following error when deploying

```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Injecting required Python packages to package...

  Error --------------------------------------------------

  nodestream is not supported by this platform
```

If I uninstall the package I can deploy again.

Any thoughts on why this is happening?

"serverless-python-requirements version: "4.3.0"

**Comment by dschep** [comment]
Well... what platform are you on?

**Comment by DrColza** [comment]
That might help alright:

```
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.9.0
     Serverless Version:     1.38.0
```

I'm going to close this "issue" because it was nothing to do with your package. Thank you 🙏 for taking the time to reply to such a vague issue though 🙄 

For anyone who might come across this post the problem was caused by a mismatch of npm modules installed globally and locally on the host system.

My resolution was to remove the local node_modules folder and run the globally installed modules instead. Your mileage may vary.
