### ISSUE TITLE
 Unzipped size must be smaller than 262144000 bytes

### ISSUE THREAD

**Issue by mdanish0320** [UnitedIncome/serverless-python-requirements#343]
This error occurs on sls deploy. I think it should work with zip: true. Code shared below

# serverless.yml
<pre><code>
service: test-big-libs 

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage,'dev'}

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
</code></pre>

# hander.py
<pre><code>
try:
  import unzip_requirements
except ImportError:
  pass

import numpy as np
import scipy as sc
import sklearn as sk 
import joblib 
import pandas as pd

import json

def test(event, context):
    body = {
        "message": "big libs works"
    }

    response = {
        "statusCode": 200,
        "body": json.dumps(body)
    }

    return response
</code></pre>

# requirements.txt
joblib==0.13.2
numpy==1.16.2
pandas==0.24.2
python-dateutil==2.8.0
pytz==2019.1
scikit-learn==0.20.3
scipy==1.2.1
six==1.12.0
sklearn==0.0

**Comment by mdanish0320** [comment]
this solves my problem

<pre><code>
package:
  exclude:
    - node_modules/**
    - venv/**

</code></pre>

**Comment by mdrijwan** [comment]
excluding node_modules doesn't work for me as i need a package. without it i get module not found error! what's the solution?

**Comment by Nithish-Evoltech** [comment]
After searching on web i found the solution.

What happens is that when deploying your application, the serverless bundle all functions and upload every function with the size of all functions all together.

So, if you have 50 function in your serverless.yml file, all them will be packaged and upload.

Let's imagine that you have 50 functions, everyone with 1MB. When deploying we will have a bundle with 50MB for every function, instead of 1MB.

This can be easily fixed adding the property "individually" in our serverless file:

package:
  individually: true
Documentation can be found [here](https://www.serverless.com/framework/docs/providers/aws/guide/packaging#packaging-functions-separately):

**Comment by kannan007** [comment]
@Nithish-Evoltech  i have given individually set to true only yet my each lambda crosses more than 100MB any solution for this?

**Comment by g-jindal2001** [comment]
@kannan007 Any updates on this issue?

**Comment by flashcrow2000** [comment]
I'm seeing the same issue, for a basic serverless setup, with 4 methods and a custom authorizer, maybe around 100 lines of code in total. reported size is 91.5 MB per function, with `individually` set to true.

**Comment by flashcrow2000** [comment]
in my case, it looks like the function archive also contains the aws terraform provider

**Comment by daiho-nfq** [comment]
> excluding node_modules doesn't work for me as i need a package. without it i get module not found error! what's the solution?

hi 👋 
How is your issue? Do you have any solutions? I have the same issue as you

**Comment by flashcrow2000** [comment]
> > excluding node_modules doesn't work for me as i need a package. without it i get module not found error! what's the solution?
> 
> hi 👋 How is your issue? Do you have any solutions? I have the same issue as you

Hava you tried using the `pattern` option to exclude `node_modules` but include the packages you need in your code?

**Comment by daiho-nfq** [comment]
> > > excluding node_modules doesn't work for me as i need a package. without it i get module not found error! what's the solution?
> > 
> > 
> > hi 👋 How is your issue? Do you have any solutions? I have the same issue as you
> 
> Hava you tried using the `pattern` option to exclude `node_modules` but include the packages you need in your code?

I see that solution but im not sure, I use serverless with nestjs and prisma. After generating prisma, the @prisma/client is stored in `node_modules`, if I exclude module, there will be an error ` 
![image](https://user-images.githubusercontent.com/61769800/216356627-df984a9f-6286-41d8-9fc6-885d9c39e7fc.png)

**Comment by flashcrow2000** [comment]
so try to include @prisma/client only. check the pattern samples, there is one with exactly this scenario, where node_modules is removed, except one folder
    On Thursday, February 2, 2023 at 04:48:26 PM GMT+2, htdai ***@***.***> wrote:  
 
 





excluding node_modules doesn't work for me as i need a package. without it i get module not found error! what's the solution?


hi 👋 How is your issue? Do you have any solutions? I have the same issue as you


Hava you tried using the pattern option to exclude node_modules but include the packages you need in your code?


I see that solution but im not sure, I use serverless with nestjs and prisma. After generating prisma, the @prisma/client is stored in node_modules, if I exclude module, there will be an error `
