### ISSUE TITLE
Windows packaging is very slow

### ISSUE THREAD

**Issue by blackmamo** [UnitedIncome/serverless-python-requirements#348]
My making two changes, one in configuration and one in the source code of this plugin, I have reduced my packaging time from over 30s to less than 10s.

As the number of dependencies increases this difference would grow. I only have 7 dependencies and 1 dev dependency at present.

I have created a PR to use junction instead of copy https://github.com/UnitedIncome/serverless-python-requirements/pull/347

**Comment by bsamuel-ui** [comment]
Closing as fix was merged and released; happy to reopen if there are still issues.
