### ISSUE TITLE
Leverage lambda-packages

### ISSUE THREAD

**Issue by simplesteph** [UnitedIncome/serverless-python-requirements#35]
I've come across the problems of dependencies that need to be compiled on an AWS instance in order to be run

This project solves it already: https://github.com/Miserlou/lambda-packages

It seems the Zappa framework has logic in place to do some dependency replacement...
https://github.com/Miserlou/Zappa#initial-deployments

```
To explain what's going on, when you call deploy, Zappa will automatically package up your application and local virtual environment into a Lambda-compatible archive, replace any dependencies with versions precompiled for Lambda, set up the function handler 
```

 could this plugin do the same?

**Comment by dschep** [comment]
What libraries are you having issues with? Have you tried the dockerized build support? https://github.com/UnitedIncome/serverless-python-requirements#cross-compiling

**Comment by simplesteph** [comment]
@dschep THANK YOU SO MUCH for making me try again. The library is `Pillow`
So it works when using Docker.

The issue I had then is that if you try without Docker, then you try with Docker, it doesn't "clean" your old dependencies and therefore you run into some issues. I think cleaning the .requirements folder is key for a good user experience

**Comment by simplesteph** [comment]
I can open a separate issue for that if you want?

**Comment by dschep** [comment]
Glad you got it working! Feel free to file an issue for that. The main reason I didn't do it is performance, cleaning `.requirements` everytime would slow down subsequent deploys i think.
