### ISSUE TITLE
Unzipped size must be smaller than 85207199 bytes

### ISSUE THREAD

**Issue by sjl070707** [UnitedIncome/serverless-python-requirements#350]
sorry wasn't able to find this in the issue tracker

I have a simple testing app
I initially tested with layer but was getting Unzipped size must be smaller than 262144000 bytes.
I am now trying to deploy the app without the layer but getting another error:
 An error occurred: GetUnderscorescoreLambdaFunction - Unzipped size must be smaller than 85207199 bytes

----------------------------------------
serverless.yml
----------------------------------------
service: xgb-test 
provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  stage: dev

functions:
  get_score:
    handler: handler.get_score

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    zip: true
    dockerizePip: 'non-linux'
    slim: true

package:
  include:
    - '*.py'
    # - requirements.txt
  exclude:
    - '**/*'

----------------------------------------
requirements.txt
----------------------------------------
numpy==1.15.4
pandas==0.24.2
pymysql
xgboost

----------------------------------------
handler.py
----------------------------------------
try:
  import unzip_requirements
except ImportError:
  pass

import json
import numpy as np
import xgboost as xgb
import pymysql
import pandas as pd

def get_score( event, context):
    txt = "layer import success"
    print(txt)

    return txt

if __name__ == "__main__":
    get_score('', '')

**Comment by sjl070707** [comment]
![image](https://user-images.githubusercontent.com/11779060/56308685-e5da3080-6115-11e9-9490-9ea407bf227d.png)
![image](https://user-images.githubusercontent.com/11779060/56308717-f5597980-6115-11e9-9805-0d751c07bf88.png)

**Comment by sjl070707** [comment]
new requirements.txt

numpy==1.15.4
pandas==0.24.2
pymysql
sklearn==0.0

works as it reduces the package size

Serverless: Uploading artifacts...
Serverless: Uploading service xgb-test.zip file to S3 (22.79 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...

but xgboost package is essential :(

**Comment by sjl070707** [comment]
I got it working properly by specifying the version number for xgboost

numpy==1.15.4
pandas==0.24.2
xgboost==0.82
scipy==1.1.0
sklearn==0.0

I dunno why but it works now

**Comment by bsamuel-ui** [comment]
I know many error messages are confusing or irrelevant, but your first step debugging should be to take them at face value to see if that's the issue.

As it says, the unzipped contents are too big; I'm amazed you got it to work as some of those are very big modules.
