### ISSUE TITLE
editable flags -e in requirements.txt don't work

### ISSUE THREAD

**Issue by simplesteph** [UnitedIncome/serverless-python-requirements#36]
requirements.txt
```
-e git+git://github.com/ojii/pymaging.git#egg=pymaging
-e git+git://github.com/ojii/pymaging-png.git#egg=pymaging-png
```

throws error:
```
Serverless: Installing required Python packages for runtime python2.7...
 
  Error --------------------------------------------------
 
  Command "/Users/stephanemaarek/.pyenv/versions/2.7.12/bin/python2.7 -c "import setuptools, tokenize;__file__='/Users/blah/projects/python-s3-thumbnail/src/pymaging/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" --no-user-cfg develop --no-deps --home=/var/folders/x5/gcz23y8x62v7v2bx49rt00wr0000gn/T/tmpGP7oYR" failed with error code 1 i
```

tried both with and without docker

**Comment by simplesteph** [comment]
removing `-e` fixes the problem as a temporary fix

**Comment by defendertx** [comment]
Just wanted to add that pipenv also does not work for git due to the requirements.txt generated by pipenv having the -e flag.

For anyone needing a workaround for SSH access to GitHub, use the format `git+ssh://git@github.com/$org/$repo.git#egg=$egg`.

**Comment by lyoungblood** [comment]
@simplesteph thanks for this tip - worked for me.

**Comment by miketheman** [comment]
> I'll create a PR to fix that, but as a workaround you can just use `--editable` instead of `-e`

@jacksgt We'll be on the lookout for it! Please consider adding a test case as a separate commi, so we can rework it when #482 is merged.
