### ISSUE TITLE
possible to skip gathering of requirements?

### ISSUE THREAD

**Issue by dtenenba** [UnitedIncome/serverless-python-requirements#364]
It takes a few minutes to run `sls deploy function -f myfunction`. 
The most time seems to be spent in building my dependencies (in docker since I'm on a Mac). 
Can these be cached so that if I include some flag, this step can be skipped and just my handler code updated?

That would save me a few minutes and let me iterate much more rapidly in my development. I realize I can `invoke local`, but there are enough differences between my local environment and Lambda that I still need the reality check of actual lambda pretty frequently.

**Comment by jdufresne** [comment]
Take a look at `useStaticCache` and the other caching options listed in the README:

https://github.com/UnitedIncome/serverless-python-requirements#caching

**Comment by dtenenba** [comment]
Sorry, RTFM fail on my part.

**Comment by AndrewFarley** [comment]
The original idea behind static caching was to eventually enable it by default once any/all kinks have been worked out so people don't have to RTFM and can benefit from it automatically.

Maybe this time is approaching...?  @dschep   :)

**Comment by dschep** [comment]
@AndrewFarley right.. want to make a PR making them the default? I think i'll cut a beta release with that and a few other recent changes i've merged to test it out for a while. that seem good?
