### ISSUE TITLE
New release with the latest changes planned?

### ISSUE THREAD

**Issue by IanTayler** [UnitedIncome/serverless-python-requirements#375]
Your latest commit f39e166e8221171ec040ca37fe0f98b6ed89ad75 adds features that are really useful. I'd love to see those changes pushed to an official release.

Let me know if there's anything I can do to help with it.

**Comment by stevenolen** [comment]
I'd love to see a new release cut as well, specifically for #304!

**Comment by dschep** [comment]
thanks for the reminder to do this. I'll try to get a release out his week or next!

**Comment by tpansino** [comment]
+1 friendly reminder to do this 😉 , particularly for us poetry-using folks to take advantage of the fix in #390 .

**Comment by dschep** [comment]
Done!!! Sorry again about the delay folks, enjoy sls-py-reqs v5!
