### ISSUE TITLE
invoke local fails

### ISSUE THREAD

**Issue by Selion05** [UnitedIncome/serverless-python-requirements#382]
I tried [per function requirments](https://github.com/UnitedIncome/serverless-python-requirements#per-function-requirements)

[example](https://github.com/Selion05/sls-python-requirements-bug)
invoking the deployed verison `sls invoke -f func1` works but running  `sls invoke local -f func1` fails with 

> ModuleNotFoundError: No module named 'index'

    .serverless/
    ├── cloudformation-template-create-stack.json
    ├── cloudformation-template-update-stack.json
    ├── func1.zip
    ├── func2.zip
    ├── function1
    │   ├── requirements
    │   │   └── requirements.txt
    │   └── requirements.txt
    ├── function1-testpy-dev-func1.zip
    ├── function2
    │   ├── requirements
    │   │   └── requirements.txt
    │   └── requirements.txt
    ├── function2-testpy-dev-func2.zip
    └── serverless-state.json

Is it possible that `invoke local` uses `func1.zip` instead of `function1-testpy-dev-func1.zip`?

**Comment by dschep** [comment]
this plugin doesn't affect invoke local useage. make sure you're in a virtual env with the right dependencies installd when calling invoke local.
