### ISSUE TITLE
Install python dependencies for a Lambda Layer

### ISSUE THREAD

**Issue by aslafy-z** [UnitedIncome/serverless-python-requirements#384]
I'd like to automatically install my layer's dependencies but it seems that `serverless-python-requirements` doesn't know about them.

## Example

https://github.com/aslafy-z/serverless-layer-bug

Build with 
```
npm install
SLS_DEBUG='*' serverless package
```

The `.serverless/package/layer.zip` package does not contain the dependencies listed in `layer/python/requirements.txt`

I think it would be a great addition if this library accepts it.

**Comment by dschep** [comment]
you'll want to checkout the plugin's layer option: https://github.com/UnitedIncome/serverless-python-requirements#lambda-layer

**Comment by aslafy-z** [comment]
Sorry for being not that clear @dschep. The thing is, I'd like to use individual layers with different names and just want serverless-python-requirements to install my deps (from layers/my-layer/requirements.txt).
I would also need a way to target a specific directory within the layer (eg: layers/my-layer/python).
See https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html#configuration-layers-path

**Comment by dschep** [comment]
Ah. Yeah, individual layers isn't currently supported. Leaving closed, you can track individual layer support in #328
