### ISSUE TITLE
Prioritize function runtime over provider runtime

### ISSUE THREAD

**Issue by ed-sparkes** [UnitedIncome/serverless-python-requirements#385]
My project contains a mix of node and python, mostly node, i set the provider runtime as node then for specific functions i specify python. This is working perfectly locally when using docker but on my build server which is linux and therefore dont need to run docker i am getting an error 

`  nodejs8.10 not found! Try the pythonBin option.`

It appears in this scenario it is using provider level runtime setting to run python commands 

would it be possible to either use function level runtime or alternatively add a pythonCommand override in the plugin settings to force it back. i could set the pythonBin however this will be completely different on my local windows machine and CI server so this will not work

**Comment by ColdFire87** [comment]
@ed-sparkes I'm having the exact same issue. How did you manage to solve this? Thanks!

**Comment by ed-sparkes** [comment]
I gave up and had two separate serverless projects
