### ISSUE TITLE
platform_system restrictions are ignored

### ISSUE THREAD

**Issue by jonfreedman** [UnitedIncome/serverless-python-requirements#391]
As per [PEP 508](https://www.python.org/dev/peps/pep-0508/) it's possible to define requirements which are only used in certain circumstances.  We make use of this because we have a variety of python code in a single repository, for example

```
pywin32 == 224 ; platform_system == 'Windows'
```

Unfortunately when we package for AWS lambda these are included, whether we run the package script on Linux or Windows.

This is with:
    "serverless": "1.49.0",
    "serverless-python-requirements": "4.3.0"

**Comment by jonfreedman** [comment]
It looks like when the packaging is done on Linux this is respected, it would be nice if the requirements were parsed with the output OS in mind so that the zip produced on windows and linux is the same.

**Comment by dschep** [comment]
This falls into the realm of crosscompilation (admittedly, only kinda if it's just a matter of what dependencies are packaged, not needing to build binaries), but i recommend handling the same way. use the `dockerizePip` option.

**Comment by jonfreedman** [comment]
I'd love to be able to package using Docker on Windows - unfortunately our corporate policy prohibits it

**Comment by dschep** [comment]
I'm not sure of any work around for you then i'm afraid. This package does very little with actual installation of python packages, that's all left up to `pip`. :(
