### ISSUE TITLE
poetry and private repositories

### ISSUE THREAD

**Issue by username-dot-com** [UnitedIncome/serverless-python-requirements#407]
Poetry doesnt output extra index urls for having pip look at other repositories for packages by default with the export command. The `--with-credentials` flag must be set for the export command to put the extra index urls into the requirements.txt output. This broke my team's serverless deploy step since packaging couldn't be completed, because pip couldnt find the dependencies that were stored in our private pypi server.

I've currently worked around this issue by specifying our pypi source in `PIP_EXTRA_INDEX_URL` environment variable. I'm not sure this would work for people who need multiple extra sources though.

It seems an easy enough fix: use the `--with-credentials` flag when calling `poetry export`, and I'm willing to create a pr for this, unless there are repercussions to this change I'm not seeing.

**Comment by username-dot-com** [comment]
Now that I think about it, I'm pretty sure adding that command would break back compat with the 1.0.0a5 release if that matters?

**Comment by miketheman** [comment]
Hi @username-dot-com ! Thanks for offering to add that functionality.
We recently discussed poetry backwards compat in https://github.com/UnitedIncome/serverless-python-requirements/pull/446#issuecomment-587240575, and decided that we're oOK not supporting pre-1.0.0.

If you wanted to create a PR with some tests (CircleCI is the one to watch), we'd appreciate it!

**Comment by username-dot-com** [comment]
Sounds good. I'm pretty busy this week, but I should be able to get on this by sometime next week.
