### ISSUE TITLE
Support for multi-runtime repos

### ISSUE THREAD

**Issue by fernando-mc** [UnitedIncome/serverless-python-requirements#413]
When using this with a function-specific runtime setting for all function the plugin doesn't pick a Docker image.

```
Error: STDOUT: 
  
  STDERR: Unable to find image 'lambci/lambda:build-undefined' locally
```

Looks like there is an easy fix if you just specify the top level provider language as Python and then the other functions (node in my case) are specified under each function.

I don't think this really needs a fix but I ran into the above error and couldn't find a solution to it without a bit more digging.

**Comment by fernando-mc** [comment]
Looks like the solution is here: https://github.com/UnitedIncome/serverless-python-requirements/issues/80

Hopefully that helps other folks who run into the issue!

**Comment by calebschoepp** [comment]
+1 This was exactly my issue. Thanks @fernando-mc
