### ISSUE TITLE
i want to deploy my ml model on aws lambda but size of the packages is more than 500mb . how to compress this ?

### ISSUE THREAD

**Issue by dimanshu** [UnitedIncome/serverless-python-requirements#434]
here is my requirements.txt

numpy==1.14.3
https://download.pytorch.org/whl/cpu/torch-1.0.0-cp36-cp36m-linux_x86_64.whl
librosa==0.5.1
Unidecode==0.4.20
tensorboard
tensorboardX
matplotlib==2.0.2
Pillow
flask
scipy==0.19.0
tqdm
git+git://github.com/bootphon/phonemizer@master
soundfile
boto3
requests

**Comment by MMuthukrishna** [comment]
would recommend doing this
https://github.com/UnitedIncome/serverless-python-requirements#dealing-with-lambdas-size-limitations

**Comment by miketheman** [comment]
The question appears to have been answered, and there's been no follow up in some time. Closing!
