### ISSUE TITLE
codepipeline access denied issue

### ISSUE THREAD

**Issue by blomm** [UnitedIncome/serverless-python-requirements#443]
If I run `serverless deploy -s dev ` from my local machine, my function deploys with my layer (non-dockerized). Non-dockerized because they're simple packages and don't need docker, however I'm using serverless-python-requirements to put the packages in layer.

I want to do a serverless deploy on code push, so I've set up codepipeline, and all is good until the step which give me Access Denied:

>  Serverless: Packaging Python Requirements Lambda Layer... 

Question is, what is this necessary access?

![image](https://user-images.githubusercontent.com/364940/71255066-d22a3e00-2324-11ea-844f-5c54f58f75f7.png)

**Comment by blomm** [comment]
the next step was :
Serverless: Uploading CloudFormation file to S3... 
so I've added s3 * policy to the role that's executing my build

**Comment by blomm** [comment]
so yeah, my issue related to serverless permissions needed in codepipeline/codebuild... 
...there were lots of other policies that needed applying too
https://github.com/serverless/serverless/issues/1439

**Comment by bsamuel-ui** [comment]
Thanks for posting the solution!
