### ISSUE TITLE
Poetry Export no longer working

### ISSUE THREAD

**Issue by JoeyC1990** [UnitedIncome/serverless-python-requirements#445]
As per poetry's new version 1.0.0 release, the command needs to be adapted from:

`poetry export --without-hashes -f requirements.txt`

to 

`poetry export --without-hashes -f requirements.txt > requirements.txt`

otherwise the deployment fails as the requirements are just read out to stdout and they aren't currently captured.

**Comment by bsamuel-ui** [comment]
Merged commits should fix this.
