### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by dschep** [UnitedIncome/serverless-python-requirements#454]
Hey folks, as is probably evident, I don't have the time to maintain this anymore. As such, I'd like to put out a call for maintainers for this plugin. let me know if you're interested in helping.

cc(because you've contributed)
@azurelogic 
@abetomo 
@angstwad 
@mather 
@rmax 
@bsamuel-ui 
@suxor42 
@mbeltran213 
@Tethik 
@miketheman 
@wattdave 
@heri16 
@ryansb 
@cgrimal 
@kichik 
@dee-me-tree-or-love 
@alexjurkiewicz 
@andrewfarley 
@bweigel 
@squaresurf 
@david-mk-lawrence

**Comment by alexjurkiewicz** [comment]
Thanks for your time working on this plugin. It's been an invaluable tool for me in several projects ❤️

**Comment by miketheman** [comment]
Thanks for the work you've done so far! It would be helpful to understand what type of maibtainership assistance you're looking for.

**Comment by AndrewFarley** [comment]
@dschep I’d happily be a/the maintainer, I still use this actively on a number of my clients in the past and am always looking forward to using it in the future for any new projects/clients.

Because of occasional heavy workload it would be ideal if a few other people stepped up to help co-manage this to help ensure proper maintenance and support.

**Comment by abetomo** [comment]
A very useful plugin.
I will cooperate for you as much as I can.

**Comment by cgrimal** [comment]
@dschep Thanks for all the good work on this plugin. I couldn't have carried on many projects without it!
I'm not using serverless anymore at the moment, so I don't think I'll be able/motivated to help on a regular basis.

**Comment by rmax** [comment]
@dschep thank you for all your hard work!

This was my gateway drug to the serveless world :)

**Comment by dschep** [comment]
Thanks for for the support folks! @AndrewFarley & @miketheman, the main thing is responding to issues & reviewing PRs. The _main_ responsibility, imo, is ensuring the lack of regressions when doing the later. I've mostly been doing this by virtue of the integration test suite. There's already plenty of in progress PRs I have been neglecting. In terms of general improvements that a maintainer could make or should see PRs addressing are: fixing/cleaning CI process, probably switching to GH actions for all 3 OSs, and improving/changing how this plugin works with `package: individually`

**Comment by dschep** [comment]
re testing & github actions, I'd started on these two actions to enable the pipenv & poetry tests: 
https://github.com/dschep/install-pipenv-action
https://github.com/dschep/install-poetry-action

**Comment by dee-me-tree-or-love** [comment]
@dschep thanks a lot for your hard work and for maintaining this project! It was a pleasure working on it and contributing! Always keeping my eye on it, and will cooperate as much as I can also. 
Good luck with new adventures.

**Comment by bweigel** [comment]
@dschep thanks for the work you have put into this plugin. It has helped me immensely in the past. 
Unfortunately my journey has steered somewhat away from the serverless framework and I fear I could not commit to a maintainer role in a worthy way.

**Comment by bsamuel-ui** [comment]
I'm going to pick up as a maintainer on the United Income side. My first priority will be getting CI working again and relearning how this module works, as it's works without complaints for what we do and I've kinda forgotten the guts of it. If people can jump on existing PRs and issues and move them forward a bit, especially proving out that they're working, that'd help immensely.

**Comment by miketheman** [comment]
That's great @bsamuel-ui ! I can commit to taking a pass at Triaging open Issues on Monday. Will I be able to apply Labels to Issues?

**Comment by bsamuel-ui** [comment]
Um, let me see if I can add you to that. TBH, permissions systems more complicated than three octal digits tend to confuse me.

**Comment by bsamuel-ui** [comment]
@AndrewFarley I've got one more seat for repo permissions, you still game for it?

**Comment by AndrewFarley** [comment]
@bsamuel-ui Absolutely am.  Are fellow maintainers interested in having a chat channel somewhere (slack/discord/etc) so we can hash things out instead of doing it in issues in the repo?  I'd be keen to have a place to discuss things, be able to back and forth with each other to help drive things in a positive direction together.

**Comment by bsamuel-ui** [comment]
I agree; how about the serverless contributors slack? I've invited @miketheman to it as well.
