### ISSUE TITLE
Can't deploy with python3.6

### ISSUE THREAD

**Issue by cm-usuda-keisuke** [UnitedIncome/serverless-python-requirements#48]
It was failed the sls deploy with  the following message :
```
Serverless: Parsing Python requirements.txt
Serverless: Installing required Python packages for runtime python3.6...

  Error --------------------------------------------------

  pyenv: python3.6: command not found

The `python3.6' command exists in these Python versions:
  3.6.1
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.11.1
     Serverless Version:     1.18.0
```

My env is the following:
```
$ sls --version
1.18.0
$ python --version
Python 3.6.1
```

Now the 80 line of 'index.js' is written the following: 
`const runtime = this.serverless.service.provider.runtime;`
We need to set 'python3.6' for runtime, so we can't  set the python alias.

Can you change it so that it reads the alias set as below?
```
# in serverless.yml
provider:
  name: aws
  runtime: python3.6
  alias: python
```

I do not know node.js in detail, so I'd like to ask for a suitable fix.

**Comment by dschep** [comment]
Is `provider.alias` a serverless directive? Or are you asking for an option to specify the python executable this plugin should use? If it's the later I would add `custom.pythonRequirements.pythonBin` as an option.

**Comment by dschep** [comment]
Also, are you using a python installed with pyenv? Does it not install `pythonX.Y` symlinks like most python installation methods?

**Comment by cm-usuda-keisuke** [comment]
Thank you for your suggestion.
It is not a serverless directive, so I think your idea that is add `custom.pythonRequirements.pythonBin` is good.

I do not know the proportion of pyenv users and pythonX.Y users.
However I think it is better that we will be able to use this plugin in either way.

**Comment by dschep** [comment]
Cool cool. I think my weekend is gonna be super rainy and lame so I'll probably code it up then 😉

**Comment by dschep** [comment]
I've released this in version `3.0.0-beta`. It's a major version because the no deploy change is a breaking change and it's a beta because @UnitedIncome is nearing a public launch so I don't wanna pull a bunch of changes into our release.

**Comment by cm-usuda-keisuke** [comment]
Thank you for the commit!
I’m looking forward to the release.

**Comment by joelclipperton** [comment]
I got this error and found that if I didn't have python3.6 installed, i.e., there was no `/usr/local/bin/python3.6` available it wouldn't work.  Adding a link from `python3.6` to my current version worked without having to install it.

**Comment by agarhy** [comment]
Worked fot me with virtual ENV, checkout https://docs.python-guide.org/dev/virtualenvs/#lower-level-virtualenv and https://www.serverless.com/blog/flask-python-rest-api-serverless-lambda-dynamodb
create virtualenv with install requrements
switch(activate) to virtualenv "$ source venv/bin/activate" 
run $sls deploy
