### ISSUE TITLE
Check sls version on init

### ISSUE THREAD

**Issue by dschep** [UnitedIncome/serverless-python-requirements#49]

**Comment by dschep** [comment]
Did a bit of initial digging on this a while ago, not sure if that info can be found from the `serverless` object passed into the plugin :confounded:

**Comment by miketheman** [comment]
#Triage 
Going through old issues, it's unclear as to why the plugin needs to know about the version of the framework being executed.
Recommend closing this issue, and if we have a reasoning for needing to know the framework version, we can reopen this/open a new issue with the specifics.
