### ISSUE TITLE
Dockerfile question

### ISSUE THREAD

**Issue by harshthakur9030** [UnitedIncome/serverless-python-requirements#508]
Hey, 
I am curious to know where do things I install through Dockerfile go. Is it /tmp or /opt? Also, is it a bad idea to install all the application dependencies through Dockerfile?

**Comment by miketheman** [comment]
@harshthakur9030 It depends on what you mean by "application dependencies" - this plugin aims to help solve Python-based project package dependencies.
The README shows a couple of examples of using a custom Dockerfile:
https://github.com/UnitedIncome/serverless-python-requirements#native-code-dependencies-during-build
And whatever directives you provide in your custom Dockerfile is where the resulting files will be in that Docker Image - and then you can use the `dockerExtraFiles` configuration directive to instruct this plugin on which other files you may need in the lambda deployment package.

**Comment by harshthakur9030** [comment]
Got it . I am facing an issue and I am not sure if this plugin can help. I would like to use dlib library in lambda. I installed it on the docker image(lambdaci/lambda) and wrote a Dockerfile for it which I added to the serverless.yml manifest . Dlib gets imported successfully in the container but fails on lambda for some reason. Here's how I know that:
 `ImportError("/lib64/libm.so.6: version `GLIBC_2.27' not found (required by /var/task/dlib.cpython-37m-x86_64-linux-gnu.so)")`

**Comment by miketheman** [comment]
That looks like some sort of version mismatch between the GLIBC version available in the Python 3.7 and the version requested in the compiled libm.so library.

A quick google search found this article that might be useful: https://stackoverflow.com/q/54616024/244037

**Comment by harshthakur9030** [comment]
Isn't the docker image I am using(lambdaci/lambda) the same image AWS lambda uses or did I get that wrong?

**Comment by miketheman** [comment]
I tried to reproduce and couldn't - saw the same on glibc 2.17 in the image.
I guess if you can provide more reproduction details, someone could try to determine the cause - I did `pip install dlib` and the basics worked for me.

**Comment by harshthakur9030** [comment]
I needed a clean start to fix it. After a "sls remove", I'm able to import it successfully on lambda. Thanks

**Comment by miketheman** [comment]
Glad to hear it worked out!

**Comment by Aarif1430** [comment]
Hi @RealHarshThakur, I am trying to do something similar. Where I need to package pandas and dataframe-image inside docker and use that as an image in serverless. Would you mind pasting your docker file here?
## Docker
```shell
FROM lambci/lambda:build-python3.8

WORKDIR /opt
RUN mkdir -p python/lib/python3.8/site-packages
COPY requirements.txt /tmp
WORKDIR /tmp
RUN pip install -r requirements.txt --no-deps -t python/lib/python3.8/site-packages

# remove warning about cairo < 1.15.4
WORKDIR /opt/python/lib/python3.8/site-packages
```
## Serverless
```shell
custom:
  pythonRequirements:
    slim: true
    dockerizePip: true
    dockerImage: 716396069640.dkr.ecr.us-east-2.amazonaws.com/docker_custom_python:latest
```

**Comment by daxiang28** [comment]
> Hi @RealHarshThakur and @miketheman , I am trying to do something similar. Where I need to package pandas and dataframe-image inside docker and use that as an image in serverless. Would you mind pasting your docker file here?
> 
> ## Docker
> ```shell
> FROM lambci/lambda:build-python3.8
> 
> WORKDIR /opt
> RUN mkdir -p python/lib/python3.8/site-packages
> COPY requirements.txt /tmp
> WORKDIR /tmp
> RUN pip install -r requirements.txt --no-deps -t python/lib/python3.8/site-packages
> 
> WORKDIR /opt/python/lib/python3.8/site-packages
> ```
> 
> ## Serverless
> ```shell
> custom:
>   pythonRequirements:
>     slim: true
>     dockerizePip: true
>     dockerImage: **********.dkr.ecr.us-east-2.amazonaws.com/docker_custom_python:latest
> ```

@Aarif1430 Did you ever figure this out? I've been struggling to find a great example of having packages installed via the Docker image. I'm trying to figure out how best to get around the 250mb unzipped cap.
