### ISSUE TITLE
Customize requirements file name

### ISSUE THREAD

**Issue by guillaumervls** [UnitedIncome/serverless-python-requirements#51]
Hi, and thanks for the module !

Is it possible to specify the name of the requirements file as an option, instead of it necessarily being `requirements.txt` ? The `#no-deploy` option is cool but does not enable this workflow for example : www.kennethreitz.org/essays/a-better-pip-workflow (where `requirements.txt` is generated).

Did I miss something ?

Cheers

**Comment by dschep** [comment]
I've released this in version `3.0.0-beta`. It's a major version because the no deploy change is a breaking change and it's a beta because @UnitedIncome is nearing a public launch so I don't wanna pull a bunch of changes into our release.
