### ISSUE TITLE
Any performance hit for unzipping requirements?

### ISSUE THREAD

**Issue by jfgrissom** [UnitedIncome/serverless-python-requirements#52]
Hi,

Thanks for this package. It's great and working well for me.

I'm curious, are there ever issues with unzipping every time a lambda is invoked?

https://github.com/UnitedIncome/serverless-python-requirements/blob/master/unzip_requirements.py

Thanks!

**Comment by dschep** [comment]
I don't know of any specific issues, but you are are correct that there is a small performance hit when using the zip option since unzipping a file can't be done instantaneously.
