### ISSUE TITLE
5.1.1 / 5.2.0 release planning

### ISSUE THREAD

**Issue by bsamuel-ui** [UnitedIncome/serverless-python-requirements#550]
I've been neglecting this project because the async nature of Github makes it too easy to push this aside, so let's try something synchronous.

Agenda:
- also work on schedule that works for others
- figure out PRs are ready for release and what are blocked
- if there's more time, triage some issues

When: 
- Saturday Sep 19
- 10am Eastern US to 2pm

Where:
- The [serverless-contrib slack](https://serverless-contrib.slack.com/); channel is `#python-requirements`
- Shoot me an email if you need an invite.

**Comment by bsamuel-ui** [comment]
The major item blocking merging is failing tests. I've resolved some of those, but there's something very broken in #489, but less so for #490. Plan for #490 is possibly skip that test on Windows, unless I can try and reproduce the issue on a Windows box.

**Comment by lephuongbg** [comment]
@bsamuel-ui Just a gentle nudge. It would be nice if we can make a patch release with current changes in master.

**Comment by piohhmy** [comment]
@bsamuel-ui any chance we can get a version bump published with the latest changes?

**Comment by BwL1289** [comment]
@bsamuel-ui any update on version bump? such a great plugin that's used by 1000s of projects

**Comment by bsamuel-ui** [comment]
@BwL1289 @piohhmy @lephuongbg Sorry for the delay, 5.1.1 is now released.
