### ISSUE TITLE
Drop support for python 2.7

### ISSUE THREAD

**Issue by bsamuel-ui** [UnitedIncome/serverless-python-requirements#551]
We talked about supporting dropping python 2.7 and decided against it as AWS was continuing to support it natively on Lambda.

Per [this doc](https://aws.amazon.com/blogs/compute/continued-support-for-python-2-7-on-aws-lambda/), AWS will stop issuing security patches on December 31, 2020.

I propose that on Jan 1, 2021, there should be a new major release that drops python 2.7 support. Or we could do so earlier.

**Comment by miketheman** [comment]
Related: #463

**Comment by bsamuel-ui** [comment]
Closing this in favor of #463.
