### ISSUE TITLE
File Table Overflow when using package zip feature

### ISSUE THREAD

**Issue by calclavia** [UnitedIncome/serverless-python-requirements#63]
I'm getting the following error when using the package compression option. Using v2.5.0.

```
Error: ENFILE: file table overflow, open '~/lambda/.requirements/tensorflow/include/external/eigen_archive/Eigen/src/PardisoSupport/PardisoSupport.h'
```

Is there any reason why the zipping seems to not be working?

**Comment by dschep** [comment]
Hrmm.. only when zipping? Does `sls package` without the option work? I use nearly the same code as serverless itself uses to zip the service (i copy and pasted it), so I'd expect that to break in the same way.

**Comment by calclavia** [comment]
I have serverless v1.20 and yes `sls package` fails with same error.

**Comment by dschep** [comment]
Right, but does serverless's zipping of the whole service fail if you disable this plugin's zip option?

**Comment by calclavia** [comment]
@dschep Just tested. Without the zip, `sls package` works fine. With zip it, the plugin works fine.

**Comment by calclavia** [comment]
I managed to fix it via:
https://github.com/karma-runner/karma/issues/1979
http://blog.mact.me/2014/10/22/yosemite-upgrade-changes-open-file-limit

It's related to Mac OSX file limits. Consider putting this on the README if anyone else runs into the same issue! :)
