### ISSUE TITLE
Conditional Requirements for dev / test 

### ISSUE THREAD

**Issue by srizzling** [UnitedIncome/serverless-python-requirements#77]
I'm a little unsure of the workflow how I can use this plugin and custom modules.

During the development phase it is useful to create changes to a local version of the module, which is consumed during local deployments of the lambda.

Once we get to production it should use a version from our private hosted artifactory instance.

Do you know a way we could do this by having different requirements file?

**Comment by dschep** [comment]
See the [`fileName` option](https://github.com/UnitedIncome/serverless-python-requirements#customize-requirements-file-name).

**Comment by srizzling** [comment]
So during dev, I need to set that parameter to the dev-requirements.txt and during prod I  need to set that to a prod requirements file?

Is there anyway have to serverless understand that based on the stage tag?

**Comment by dschep** [comment]
Yup. Do something like this:
```yaml
custom:
  pythonRequirements:
    fileName: requirements-${opt:stage, self:provider.stage}.txt
```
