### ISSUE TITLE
Permission Denied: '/var/task/.requirements'

### ISSUE THREAD

**Issue by chasebleyl** [UnitedIncome/serverless-python-requirements#81]
I am trying to deploy and receive the following error:

```
Serverless: Installing required Python packages for runtime python3.6...
Serverless: Docker Image: lambci/lambda:build-python3.6

  Error --------------------------------------------------

  Exception:
Traceback (most recent call last):
  File "/var/lang/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/var/lang/lib/python3.6/site-packages/pip/commands/install.py", line 388, in run
    ensure_dir(options.target_dir)
  File "/var/lang/lib/python3.6/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/var/lang/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/task/.requirements'


     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           6.11.3
     Serverless Version:     1.23.0
```

My `serverless.yml` looks like:

```
...

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  ...
```

From some posts online it looks like this might be a Lambda permission issue with the `/var/` directory. What is going on here and how do I get around it?

**Comment by dschep** [comment]
Hmm.. The plugin is mounting your service dir onto `/var/tasks` so it should be able to write it. On linux it sets a `-u $UID:$GID` option on docker run. UID&GID aren't relevant on windows or mac tho so it's disabled, not sure if there are other permission issues with using this with docker on windows and I don't have a windows box to test this on, sorry :cry:

**Comment by chasebleyl** [comment]
Dang! Alright, I might have to test this on a Linux box. Thanks for reaching out.

**Comment by dschep** [comment]
See [windows & docker notes](https://github.com/UnitedIncome/serverless-python-requirements#checkered_flag-windows-dockerizepip-notes)

**Comment by friep** [comment]
@chasebleyl were you able to fix this somehow? I am seeing exactly the same error message..

**Comment by dschep** [comment]
@friep, did you try the aforementioned windows & docker notes?

**Comment by friep** [comment]
@dschep i'm actually on mac os but this was the only thing i could find, so I'm posting here. 

This is what our serverless looks like. Weirdly, it works for my colleagues who're on mac os as well, just not for me. 
`plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
(...)
`

**Comment by friep** [comment]
sorry, i just saw #111 . will move there.
