### ISSUE TITLE
Plugin leaves packaging artifacts in working dir when interrupted

### ISSUE THREAD

**Issue by brettdh** [UnitedIncome/serverless-python-requirements#82]
First, it's not ideal that the plugin puts the packaging artifacts in the working directory alongside my serverless project and sources; it would be better if there was a separate dir for the build output so that the sources were not cluttered up with them. I imagine that something about serverless or its plugin architecture (or something else) makes that difficult, so let's set that aside for now.

This didn't really cause me problems until I went to interrupt a `serverless deploy` with Ctrl-C - and I noticed that the artifacts were not cleaned up. Thankfully, they *were* cleaned up on the next deploy, but it would be better if the plugin could notice the SIGINT and clean up after itself right away.

**Comment by dschep** [comment]
They drop in your project so that you don't have to add anything to `sys.path`. Or do you know of a way to add items to a sls puck with out putting them in your working directory?

**Comment by brettdh** [comment]
I think that's the "something about serverless" that I was guessing about - that it expects plugins to do this, and doesn't provide another way for plugins to get files in the package. Hence punting on that.

My second point stands, though.

**Comment by dschep** [comment]
gotcha. missed that bit. That's a good idea :+1:

**Comment by AndrewFarley** [comment]
+1.  I noticed this numerous times often when another plugin fails or as the author of this bug described, I CTRL-C because I need to cancel mid-stream to fix a bug before deploying.

**Comment by AndrewFarley** [comment]
@dschep With us injecting stuff directly into the Zip and using .serverless folder as our scratch directory as of 4.0 this issue is close-able.  :)

**Comment by dschep** [comment]
good point @AndrewFarley
