### ISSUE TITLE
Dev requirements are included when using Pipenv

### ISSUE THREAD

**Issue by Tethik** [UnitedIncome/serverless-python-requirements#87]
When generating requirements.txt from a pipenv/pipfile, development dependencies are perhaps unnecessarily included. The package size could be reduced by avoiding this somehow.

Unfortunately pipenv does not support locking develop dependencies: https://github.com/kennethreitz/pipenv/issues/245

**Comment by dschep** [comment]
Huh, I'm on the side of the folks who expected `lock -r` to omit dev dependencies. That script in a comment on that PR may be useful.

**Comment by Tethik** [comment]
Same! 

Another approach I was thinking of was to do something like:
```bash
mkdir tmp
cp Pipfile.lock tmp/ && cd !$
pipenv install # without dev 
pipenv run pip freeze > requirements.txt 
```
However that will leave behind an unused virtualenv, as well as download the requirements twice.

**Comment by kadrach** [comment]
This is fixed by updating pipenv.

**Comment by dschep** [comment]
Awesome! Thanks for pointing tha tout @kadrach

**Comment by Tethik** [comment]
Yep! Works for me now too with pipenv v8.3.2 and I can happily use the Pipfile instead of requirements.txt

**Comment by heri16** [comment]
Might need to reopen this issue due to packages like Cython which is required during the build process. https://github.com/UnitedIncome/serverless-python-requirements/issues/113
